[package]
name = "rkyv_codec"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Some adaptors to stream rkyv Archives over AsyncRead and AsyncWrite"
repository = "https://github.com/zyansheep/rkyv_codec"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv = { version = "0.7.33", features = ["validation"] }
bytecheck = "0.6.7"
futures = "0.3.21"
pin-project = "1.0.10"
thiserror = "1.0.30"
unsigned-varint = { version = "0.7.1", features = ["futures"] }
futures_codec = { version = "0.4.1", optional = true }
bytes = { version = "0.5.5", optional = true }

[dev-dependencies]
async-std = { version = "1.10", features = ["attributes"] }

[features]
default = ["futures_stream"]
futures_stream = ["futures_codec", "bytes"]

[package.metadata.nix]
build = true
nativeBuildInputs = [
	"cargo-edit",
]
buildInputs = []
runtimeLibs = []
toolchain = "nightly"
devshell = {name = "rust-shell" }
